"""Initial Migration

Revision ID: e98f4a38afc4
Revises: 51f143724a15
Create Date: 2018-09-10 09:49:22.671058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98f4a38afc4'
down_revision = '51f143724a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'pass_secure')
    # ### end Alembic commands ###
