"""Initial Migration

Revision ID: f423656f6941
Revises: f0fe93b6755c
Create Date: 2018-09-11 18:51:33.333108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f423656f6941'
down_revision = 'f0fe93b6755c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category', sa.String(length=255), nullable=True))
    op.drop_column('categories', 'catergory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('catergory', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('categories', 'category')
    # ### end Alembic commands ###
